################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@local= http://localhost:{{$dotenv PORT}}/api


### get all tag
GET {{local}}/tag