################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@local= http://localhost:{{$dotenv PORT}}/api


------------------TAG ROUTE------------------

### get all tag
GET {{local}}/tag

### create tag
POST {{local}}/tag
Content-Type: application/json

{
    "name": "coucou",
    "color" : "red"
}

### modify tag
PUT {{local}}/tag/38
Content-Type: application/json

{
    "name": "coucou",
    "color" : "erd"
}   

### delete tag
DELETE {{local}}/tag/10



----------------TODO ROUTE------------------

### get all todo
GET {{local}}/todo


### create todo
POST {{local}}/todo
Content-Type: application/json

{
    "description": "done a todo",
    "done" : true
}

### modify todo
PATCH  {{local}}/todo/50
Content-Type: application/json

{
    "description": "write a todo",
    "done" : false
}


### delete todo
DELETE {{local}}/todo/1


### get todo by id
GET {{local}}/todo/1


-----------category ROUTE------------------



### get all categorie
GET {{local}}/category


### create category
POST {{local}}/category
Content-Type: application/json

{
    "name": "coucou",
    "color" : "red"
}

### modify category
PATCH {{local}}/category/38
Content-Type: application/json

{
    "name": "write those routes",
    "color" : "blue"
}


### delete category
DELETE {{local}}/category/2


### get todo by id
GET {{local}}/category/1



---------------content_types-------------------------

### get all content_types
GET {{local}}/contentType




### create content_types
POST {{local}}/contentType
Content-Type: application/json

{
    "name": "coucou",
    "css" : "red"
}


### modify content_types
PATCH {{local}}/contentType/4
Content-Type: application/json


{
     
        "name": "blockquote",
        "css" : ""
    
}

### delete content_types

DELETE {{local}}/content_types/2




------------------memo route------------------

 
### get all memo
GET {{local}}/memo
 

### get one by slug
GET {{local}}/memo/base-ansible-

### get all memo with tag
GET {{local}}/memo/all

### get memo by id
GET {{local}}/memo/58


### create memo
POST {{local}}/memo
Content-Type: application/json

{
    "title": "j'apprends l'admin sys",
    "contents" : [
        {
            "content" : "rm -rf /",
            "type_id" : 2
        },
        {
            "content" : "sudo rm -rf /",
            "type_id" : 2
        }
    ],
    "categoryId"  : 9,
    "tagsIds" : [57, 58]
}


### modify memo
PATCH  {{local}}/memo/16
Content-Type: application/json

{
    "title": "new title",
    "contents" : [
        {
            "content" : "coucou",
            "type_id" : 1
        },
        {
            "content" : "new coucou",
            "type_id" : 2
        }
    ],
    "categoryId"  : 8,
    "tagsIds" : [38 , 37]
}

#### delete memo
DELETE {{local}}/memo/16




------------------memo-Content route------------------

### get all memo-Content
GET {{local}}/memo_content




----------------lexicon route------------------

### get all lexicon
GET {{local}}/lexicon

### get lexicon by idf
GET {{local}}/lexicon/1

### create lexicon
POST {{local}}/lexicon
Content-Type: application/json

{
    "word": "ansible",
    "definition" : "outil de déploiement",
    "category_id" : 8
}

### modify lexicon
PATCH {{local}}/lexicon/1
Content-Type: application/json

{
   
    "definition" : "blue",
    "category_id" : 8
}

### get all category
GET {{local}}/category



------------------link route------------------

### get all link
GET {{local}}/link


### get link by id
GET {{local}}/link/1


### create link
POST {{local}}/link
Content-Type: application/json

{
    "memo_id": 46,
    "name": "ansible",
    "url" : "https://www.ansible.com/"
}

### modify link
PATCH {{local}}/link/4
Content-Type: application/json

{
    "memo_id": 46,
    "name": "ansible2",
    "url" : "https://www.ansible.com/"
}











